name: 'Datalad windows deploy test'
on:
  push:
    branches: [ main, git-annex, tests]
  pull_request:
    branches: [ main ]
jobs:
  deploy_windows:
    runs-on: windows-latest
    env:
      SECRET_KEY: ${{ secrets.ssh_key }}
      GIT_USERNAME: ${{ inputs.name }}
      GIT_EMAIL: ${{ inputs.email }}
      AWS_ACCESS_KEY_ID: ${{ secrets.s3_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.s3_secret_key }}
      GIT_TOKEN: ${{ secrets.git_token }}
      DATALAD_LOG_LEVEL: debug
    steps:
      - name: setup python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.11
      - bane: setup_ssh
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ github.event.repository.private && secrets.CNEUROMOD_BOT_SSH_KEY || secrets.CNEUROMOD_USER_BOT_SSH_KEY }}
          ssh-host: github.com
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ github.event.repository.private && secrets.CNEUROMOD_BOT_SSH_KEY || secrets.CNEUROMOD_USER_BOT_SSH_KEY }}
      - name: setup datalad
        run: |
          python -m pip install datalad-installer 
          datalad-installer git-annex -m datalad/git-annex:release
          git config --global filter.annex.process "git-annex filter-process"
          python -m pip install datalad pytest pytest-order ssh_agent_setup
      - name: get tests repo
        run: |
          git clone https://github.com/courtois-neuromod/actions-datasets.git /tmp/actions
          git -C /tmp/actions checkout test_windows
      - name: debug
        run: |
          git --version
          git-annex version
          datalad wtf
      - name: "debug2"
        run: git clone git@github.com:${{ github.repository }}.git
      - name: "debug2"
        run: datalad -l 9 install -s git@github.com:${{ github.repository }}.git
      - name: "Test deploy"
        run: python -m pytest -v --full-trace --log-cli-level=WARNING /tmp/actions/tests
