name: deploy and integrity test
on:
  push:
    branches: [ "main", "git-annex"]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    uses: courtois-neuromod/actions-template/.github/workflows/deploy.yml@main
    with:
      name: CNeuromod Bot
      email: courtois.neuromod@gmail.com
    secrets:
      ssh_key: ${{ secrets.CNEUROMOD_BOT_SSH_KEY }}
