name: 'Datalad windows deploy test'
on:
  push:
    branches: [ main, git-annex, tests]
  pull_request:
    branches: [ main ]
jobs:
  deploy_windows:
    runs-on: windows-latest
    env:
      SECRET_KEY: ${{ secrets.ssh_key }}
      GIT_USERNAME: ${{ inputs.name }}
      GIT_EMAIL: ${{ inputs.email }}
      AWS_ACCESS_KEY_ID: ${{ secrets.s3_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.s3_secret_key }}
      GIT_TOKEN: ${{ secrets.git_token }}
    steps:
      - name: setup python
        uses: actions/setup-python
      - name: setup datalad
        run: |
          python -m pip install datalad-installer
          datalad-installer git-annex -m datalad/git-annex:release
          python -m pip install datalad
      - name: "setup gh ssh"
        run: |
          mkdir -p /root/.ssh/
          ssh-keyscan -H github.com | install -m 600 /dev/stdin /root/.ssh/known_hosts
      - name: "Test deploy"
        run: |
          pytest --log-cli-level=WARNING /actions/tests
