name: deploy and integrity test
on:
  push:
    branches: [ "main", "git-annex"]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    uses: courtois-neuromod/actions-template/.github/workflows/deploy.yml@main
    secrets:
      ssh_key: ${{ github.event.repository.private && secrets.CNEUROMOD_BOT_SSH_KEY || secrets.CNEUROMOD_USER_BOT_SSH_KEY }}
