name: 'Datalad windows deploy test'
on:
  push:
    branches: [ main, git-annex, tests]
  pull_request:
    branches: [ main ]
jobs:
  deploy_windows:
    runs-on: windows-latest
    env:
      SSH_PRIVATE_KEY: ${{ github.event.repository.private && secrets.CNEUROMOD_BOT_SSH_KEY || secrets.CNEUROMOD_USER_BOT_SSH_KEY  }}
      GIT_USERNAME: ${{ inputs.name }}
      GIT_EMAIL: ${{ inputs.email }}
      AWS_ACCESS_KEY_ID: ${{ secrets.s3_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.s3_secret_key }}
      GIT_TOKEN: ${{ secrets.git_token }}
      DATALAD_LOG_LEVEL: debug
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: setup python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.11
      - name: setup_ssh
        shell: bash
        run: |
          mkdir -p $HOME/.ssh
          ssh-keyscan -H -t rsa github.com >> $HOME/.ssh/known_hosts
      - name: setup datalad
        run: |
          python -m pip install datalad-installer 
          datalad-installer git-annex -m datalad/git-annex:release
          git config --global filter.annex.process "git-annex filter-process"
          python -m pip install datalad pytest pytest-order ssh_agent_setup
      - name: "Test deploy"
        shell: bash
        run: |
          git clone https://github.com/courtois-neuromod/actions-datasets.git /tmp/actions
          git -C /tmp/actions checkout test_windows
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "$SSH_PRIVATE_KEY" | ssh-add - >/dev/null

          git clone git@github.com:${GITHUB_REPOSITORY}.git
          pytest -v --full-trace --log-cli-level=WARNING /tmp/actions/tests/deploy
