name: Release workflow

on:
  release:
    types: [published]

jobs:
  upload-to-zenodo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: git config --global user.email "me@git.com"
      - run: git config --global user.name "Github Almighty"
      - name: publish on Zenodo
        uses: BIDS-flux/datalad-zenodo-upload@main
        id: integration
        with:
          sandbox: true
          zenodo_token: ${{ secrets.ZENODO_SANDBOX_API_TOKEN }}

      - name: Outputs Zenodo records.
        run: |
          echo "zenodo_doi = ${{ steps.integration.outputs.zenodo_doi }}"
          echo "zenodo_url = ${{ steps.integration.outputs.zenodo_url }}"
          echo "archive_url = ${{ steps.integration.outputs.archive_url }}"
